#ifndef DEFINITIONS_H
#define DEFINITIONS_H

#define CONSTRUCTOR 1
#define GENERATED_CONSTRUCTOR 2
#define DEFAULT_CONSTRUCTOR 4
#define STATIC_INIT 8
#define GENERIC_METHOD 16
#define INHERITED_METHOD 32
#define OVERRIDDEN_METHOD 64
#define OVERLOADED_METHOD 128
#define INTERFACE_METHOD 256
#define FINAL 512
#define STATIC 1024
#define ANONYMOUS 2048
#define FINAL 4096
#define ABSTRACT 8192

#endif